export const homeObjOne = {
    id: 'about', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: 'Full Stack Web Developer',
    description: 'Graduated Lambda School for Web Development in 2021. Worked as a Senior Advisor with Apple through the AppleCare division. Also worked as an F15C Avionics Technician with the U.S. Air Force.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-4.svg').default, 
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover', 
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Projects',
    headline: 'Check Out My Work',
    description: 'Here is a link to access some of the projects that I have worked on.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-1.svg').default, 
    alt: 'Car2',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'services', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Contact',
    headline: 'Get In Touch',
    description: 'Here is a link to get in contact with me.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-6.svg').default, 
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};